roboflow/roboflow-python

requirements.txt
roboflow/__init__.py
roboflow/core/project.py
roboflow/core/version.py
roboflow/core/workspace.py
roboflow/models/classification.py
roboflow/models/object_detection.py

- added fields to version() and workspace() classes. 
- changed .project() method to return right version of the class
- other smaller changes

final changes to pip package

---

requirements.txt
roboflow/core/project.py

- added uploading of directories 
- check to see if it's an image, skips over files in directory that are not valid file formats.

added batch uploading with directories

---

roboflow/core/version.py

Download a version in the specified format, if it has already been exported

Download Version

---

roboflow/core/project.py
setup.py

`annotation_path` was on the wrong white spacing tab and the `if not success` condition was triggering while `annotation_path` was not defined.
moved `annotation_path` one tab over so that it was would safe in the `if annotation_path is not None` logic.
not sure on best testing practices so am submitting PR for now.

fixed conditional flow spacing

---

roboflow/core/version.py

Adds support for upcoming custom training of YOLOv7 via data export format.

Add yolov7 format support

---

roboflow/__init__.py
roboflow/models/object_detection.py

Passthrough api_keys for samples that we use in notebooks. These will be whitelisted on the api side

passthrough api_key for sample api_keys

---

roboflow/models/classification.py
roboflow/models/object_detection.py

Provide a variable address of your local deployment server.
Fixes https://github.com/roboflow-ai/roboflow-bugtracker/issues/188

Variable Local Model Address

---

README.md

Create a git hook to run the formatter + code quality tests

Git hooks - Pre commit

---

roboflow/util/prediction.py
setup.py

Motivated by https://roboflow.slack.com/archives/C02N3MPGPB2/p1662741106737509
Will potentially be following on with more changes after discussion, but didn't want to loose the minor improvement so far

Inference Improvements

---

Dockerfile.dev
README.md
setup.py

Created `Dockerfile.dev` to allow us to quickly spin up a docker container with all the requirements deps to dev. Follow up to #48 
```bash
docker build -t roboflow-python -f Dockerfile.dev .
docker build  -t roboflow-python --build-arg PYTHON_VERSION=3.9 -f Dockerfile.dev .
docker run --rm -it \
-v $(pwd)/:/worspace/ \
roboflow-python 
```

Added Dockerfile.dev

---

roboflow/config.py
roboflow/core/version.py
roboflow/models/instance_segmentation.py
roboflow/util/image_utils.py
roboflow/util/prediction.py
tests/__init__.py
tests/models/test_instance_segmentation.py
tests/util/test_image_utils.py

This adds Instance Segmentation functionality to the python pip package. I also did a small bit of refactoring but tried to avoid going wild.
A couple unit tests have been added. I also tested the new functionality manually via:
```
import os
ROBOFLOW_API_KEY = os.environ.get("ROBOFLOW_API_KEY")
WORKSPACE_NAME = os.environ.get("WORKSPACE_NAME", "")
PROJECT_NAME = os.environ.get("PROJECT_NAME")
PROJECT_VERSION = os.environ.get("PROJECT_VERSION", "1")
LOCAL_IMAGE = "<local image path>"
HOSTED_IMAGE = "<remote image url>"
rf = roboflow.Roboflow(api_key=ROBOFLOW_API_KEY)
workspace = rf.workspace()
print(f'workspace: {workspace}')
project = rf.project(PROJECT_NAME)
print(f'project: {project}')
project.versions() …
```

Enter: Instance segmentation

---

README.md
roboflow/config.py
roboflow/core/version.py
roboflow/models/inference.py
roboflow/models/instance_segmentation.py
roboflow/models/semantic_segmentation.py
roboflow/util/image_utils.py
roboflow/util/prediction.py
tests/models/test_instance_segmentation.py
tests/models/test_semantic_segmentation.py
tests/util/test_image_utils.py

This adds Semantic Segmentation functionality to the python pip package. I also started a bit of a model refactor by abstracting a lot of the re-usable code that I wrote in the Instance Segmentation PR. The goal is to keep taking this further to simplify and DRY up the other models.
I tested manually on my local machine and ran the unit tests.
Once this is merged and pushed to pypi, we will need to create/update the docs that are displayed on semantic segmentation projects.

Enter: Semantic segmentation

---

setup.py

need to uptick minor version number for latest merges to go live into pypi

upticking minor version number for pypi deploy

---

roboflow/config.py
roboflow/core/workspace.py
roboflow/util/two_stage_utils.py
setup.py

Users can specify their two model names and versions to do two stage inference.
No new dependencies.
Tested for different model types and various parameter validation (`None` type, not default type, etc.)
-   [x] Docs updated? Will update docs with new method param upon merge.

Two stage detection method

---

roboflow/core/project.py
roboflow/core/version.py
setup.py
tests/helpers.py

Added bindings for new Roboflow API to upload model weights for a version. 
Tested locally by uploading a dummy file via new endpoint.

Added model upload to versions

---

.github/workflows/publish.yml
Makefile
roboflow/__init__.py
setup.py

This PR adds a GH action to automatically publish on PyPi **when we create a new release**.
I've added my PyPi tokens in the repo's secrets

GH action for publishing on PyPi

---

README.md

In the README:
- fix a few typos
- improve formatting like spacing, trailing whitespace
- add "bash" to code blocks lacking it
- improve language in a few places
Was going through this project for the first time and noticed a few things seemed off in the README, so I took a pass through it. Hope this helps; if it doesn't please ignore!

Cleanup the README by fixing various typos and improving formatting.

---

roboflow/__init__.py

Retry auth key validation in the event of a sparsely occurring server authentication failure

Retry Key Validation in Sparse Server Failure Case

---

roboflow/__init__.py

Version 0.2.21

---

roboflow/core/workspace.py

updated input handling to support cv2 ndarrays so that an RSTP stream could send frames via VideoCapture() directly to the active_learning() function.

Rstp stream support

---

roboflow/__init__.py
roboflow/core/workspace.py

Made a try + exception for a print statement.
Made a slight change to a print statement so the application doesn't break when reading IP camera streams.
No dependency changes.
This was tested on Ubuntu 20.04 while processing IP camera streams and globbed files. Testing on another Linux env would be smart.

Print Statement Try/Exception for Workspace.py

---

roboflow/config.py
roboflow/core/version.py

Contains code for uploading new models to Roboflow - exercises best practices for securely transferring model data.

New deploy() method for uploading external models

---

roboflow/__init__.py
roboflow/core/project.py
roboflow/core/version.py
tests/helpers.py

The Roboflow core application added better deployment monitoring status for external model uploads. We route to those here

New Deployment Status Routes

---

roboflow/__init__.py
roboflow/core/version.py

Ultralytics updated their model object variable types, breaking our external model deploy pathway. In this PR, we fix those issues.

Fix Ultralytics Upload Parse

---

roboflow/__init__.py

Release bump

---

roboflow/__init__.py
roboflow/core/version.py

WIP: Added support for yolov7-seg deploys (currently identical to yolov5 deploys)
WIP

YOLOv7-Seg Deploy

---

roboflow/core/version.py

Solving problems with https://github.com/roboflow/roboflow-python/issues/118

Fix for #118

---

roboflow/__init__.py

bump version to 0.2.32

---

README.md
roboflow/__init__.py

This PR introduces a new upper level `download_dataset` method and cleans up the README to be more up to date with what is possible and removes some of the older fluff
Docs update

Readme refresh

---

roboflow/__init__.py
roboflow/config.py

Updates config location to be inclusive of Windows machines.
-   [ x] Bug fix (non-breaking change which fixes an issue)

Fix windows conf

---

roboflow/__init__.py
roboflow/core/version.py

API wrapping for the download of pytorch model weights
-   [x ] New feature (non-breaking change which adds functionality)

PT Weights Download

---

roboflow/__init__.py

bump version for release

---

README.md

This PR adds a new banner to the project `README.md`.

Add new banner image

---

README.md

-   [X] Docs updated? What were the changes: Simple readme update for supervision

docs: 📝 adding supervision into readme section

---

.devcontainer/bashrc_ext
.devcontainer/devcontainer.json
.devcontainer/docker-compose.yaml
.vscode/settings.json
CONTRIBUTING.md
Dockerfile.dev
README.md

Adds a devcontainer to this repo.
https://www.loom.com/share/a183c4a351ed4700a79476fedf08ab9b
-   [x] Improve development environment
Works on my machine :-)

Add devcontainer

---

README.md

This PR changes the contributing link from a relative to an absolute link in the project `README.md`. This was proposed in #187 (credit goes to them!) but no CLA was signed with the contribution.

Update contributing link

---

.gitignore
roboflowpy.py
tests/manual/debugme.py
tests/manual/download.sh
tests/manual/login.sh
tests/manual/upload.sh
tests/manual/useprod
tests/manual/usestaging

This PR adds `/roboflowpy.py` and shell tests in `/tests/manual`
* `/roboflowpy.py` is a command line tool that can login, download and upload from the command line 
* `/tests/manual` contain quick shell scripts that use that.
* Also `/tests/manual/debugme.py` can also pass parameters to `/roboflowpy.py` in a debug-friendly way
There is no added functionality for the end user. Just sharpening the axe for better productivity deving locally.
Further explanation on what's going on here:
https://www.loom.com/share/c7ab41809fc6455dbfc6df5db1f3f2e2
https://www.loom.com/share/be37c3de7fea464cb0ffc9a0c394276c
-   [x] Improve dev env
Works on my machine
We won't be deploying this

Sharpen the axe - shell tests baked in

---

roboflow/core/version.py
tests/test_version.py

Just the bump of `ultralytics` happened at training side - we are consistently applying to all dependent repositories.
YOUR_ANSWER
N/A

Suggest users new version of ultralytics package

---

roboflow/__init__.py
roboflow/models/classification.py

Updated init for classification model to enable local inference
Tested locally

Local Classification Inference

---

roboflow/core/workspace.py

Please include a summary of the change and which issue is fixed or implemented. Please also include relevant motivation and context (e.g. links, docs, tickets etc.).
YOUR_ANSWER

Add fix for problem with active learning paths grabbing

---

roboflow/__init__.py

Bump version for release 1.1.17

Bump version for release 1.1.17

---

CLI-COMMANDS.md
roboflow/__init__.py
roboflow/core/version.py
roboflow/roboflowpy.py

New format alias for `yolov9` needs the same treatment as `yolov7`.
-   [x] New Feature
Tony tested locally pointing to production
Deploy to pip
- Not needed

YOLOv9 Export Format

---

roboflow/__init__.py
roboflow/core/version.py

Add ability to deploy yolov9 models

YOLOv9 Deploy

---

roboflow/__init__.py

Bump version

---

roboflow/__init__.py
roboflow/core/version.py
roboflow/roboflowpy.py

When uploading custom model weights, optionality to specify the filename of the weights file.
Tested with CLI and successfull uploaded model weights

specify model weights file name for uploading custom weights

---

roboflow/__init__.py
roboflow/config.py
roboflow/core/version.py
roboflow/models/classification.py
roboflow/models/inference.py
roboflow/models/keypoint_detection.py
roboflow/models/video.py
roboflow/roboflowpy.py

This PR adds support for classification video processing with the Roboflow Video Inference API. It also introduces a new `KeypointDetectionModel` class that can be used for video processing.
```python
rf = Roboflow(api_key="API_KEY")
project = rf.workspace().project("juice-box-quality-assurance")
model = project.version("1").model
job_id, signed_url, expire_time = model.predict_video(
"raccoon.mp4",
fps=5,
prediction_type="batch-video",
)
results = model.poll_until_video_results(job_id)
print(results)
```
Where the project is either a keypoint or a classification model.
N/A
N/A

Add support for classification and keypoint video processing

---

roboflow/core/project.py
roboflow/core/version.py
roboflow/core/workspace.py
roboflow/models/video.py

Mypy found a lot of issues, but many are just typing inconsistencies.
This PR focus on real obvious bugs.
I'm sure other errors cause minor bugs too, but later I'll take on these improvements.
* Using demo keys would break the `Version(...)` init because of missing `public` kwarg.
* Exceptions being raised as strings are not supported anymore (since Python 3?).
* `clip_compare` function was broken because of a missing arg.
* [`urljoin`](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urljoin) accept a third arg `allow_fragments`. We're not passing `api_key` in these requests, not sure if they're working.
* Video `.poll_until_results()` was broken because of wrong call to `.poll_for_results()`.
Pass on CI.

Fix all obvious bugs found by mypy

---

roboflow/core/version.py
roboflow/models/classification.py
roboflow/models/instance_segmentation.py
roboflow/models/keypoint_detection.py

Fix the `local` arg type. It should be an optional string, not a bool.
Ref https://github.com/roboflow/roboflow-python/issues/271
Mypy like it.

Fix `local` type

---

.pre-commit-config.yaml
CONTRIBUTING.md
README.md
roboflow/__init__.py
roboflow/core/project.py
roboflow/core/version.py
roboflow/core/workspace.py
roboflow/models/classification.py
roboflow/models/instance_segmentation.py
roboflow/models/keypoint_detection.py
roboflow/models/object_detection.py
roboflow/models/semantic_segmentation.py
roboflow/util/folderparser.py
roboflow/util/image_utils.py
setup.py
tests/__init__.py
tests/models/test_instance_segmentation.py
tests/models/test_object_detection.py
tests/test_version.py
tests/util/test_folderparser.py

This PR enhances the project's development setup and improves documentation accuracy. The main changes include:
- Adding comprehensive installation instructions for contributors to CONTRIBUTING.md
- Adding a pre-commit hooks setup guide to CONTRIBUTING.md
- Updating package dependencies for pre-commit
- Integrating pyupgrade hook and run it on the project
- Updating README to align installation instructions with `setup.py`
-   [x] Docs updated? What were the changes:
-   Added comprehensive installation instructions to CONTRIBUTING.md, including virtual environment …

chore: enhance pre-commit setup and correct installation instructions

---

roboflow/__init__.py

remove default to environment variable when initializing
-   [ X] Bug fix (non-breaking change which fixes an issue)
CI tests

remove loading api key from env variable when initializing api key

---

roboflow/config.py
tests/manual/useprod
tests/manual/usestaging

ddploy.roboflow.com ==> roboflow.cloud
Tested in staging.

change domain name for dedicated deployment

---

roboflow/__init__.py
roboflow/adapters/deploymentapi.py
roboflow/deployment.py

Add args for dedicated deployment: duration, deletion_on_expiration
Tested in staging.

Add args for dedicated deployment: duration, deletion_on_expiration

---

roboflow/__init__.py
roboflow/adapters/deploymentapi.py
roboflow/deployment.py
roboflow/roboflowpy.py

1. update arguments for dedicated deployment
2. add roboflow --version
3. add roboflow whoami
4. bump version to 1.1.41
Tested locally

Dedicated deployment: update args; add roboflow --version and whoami

---

roboflow/__init__.py

Release v1.1.42 for video infer bug fix by @PacificDou

new release for video job bugfix

---

roboflow/__init__.py
roboflow/core/version.py

Adds support for yolov11 model deploys.
Tested locally running the python package, and deploying a yolov11 model.
n/a

Add yolov11 model deploy support

---

roboflow/__init__.py

Bump package version

---

roboflow/__init__.py

Bump to release https://github.com/roboflow/roboflow-python/pull/338.
CI pass.

Version bump: 1.1.49

---

roboflow/__init__.py

Fix `download_dataset` does not respect `ROBOFLOW_API_KEY`. Tested authentication with `ROBOFLOW_API_KEY` and `login`. Both work.

fix `download_dataset` does not respect `ROBOFLOW_API_KEY`

---

roboflow/adapters/deploymentapi.py
roboflow/deployment.py

dedicated deployment: 
1. add pause and resume features
2. set `creator_email` as required when create a new dedicated deployment
Tested in staging

dedicated deployment: add pause resume
