roboflow/roboflow-python

roboflow/core/project.py
The image and annotation upload functions were using. hardcoded endpoint instead of the `API_URL` config parameter; which makes it hard to use for testing in development environments.
=> respect API_URL config parameter for all API calls

roboflow/core/version.py, roboflow/models/classification.py
this fixes https://github.com/roboflow-ai/roboflow-bugtracker/issues/227
I tested this by running the following code from the bug report locally:
```
rf = Roboflow(api_key="2lwa7Lfz2bFil1jbFOF5")
project = rf.workspace("mohamed-traore-w4h8y").project("bug-test-pvmy6")
dataset = project.version(1).download("multiclass")
```
After removing the local keyword arg, it downloaded the dataset correctly.
=> don't pass `local` keyword arg to `ClassificationModel`

.github/workflows/test.yml
Trying to fix failed GitHub action run with error
```
The process '/usr/bin/git' failed with exit code 1
````
See [this one](https://github.com/roboflow-ai/roboflow-python/actions/runs/3055449080)
=> Fix crashed github action

README.md
The example code in the README doesn't define `model` before using it.
=> Define model before using it in the README

roboflow/core/dataset.py, roboflow/core/version.py, tests/helpers.py, tests/test_project.py, tests/test_version.py
While adding `Version.export()`, and thinking about how that could be integrated into `Version.download()`, I decided to also clean that method up a bit to make it more parseable and testable. I think I also fixed a couple bugs in the process (and hopefully didn't introduce any 😅)
I've only tested with the new unit tests so far. We should definitely manually test. I'd love to pair on that.
=> Add simple version.export() functionality and clean up version.download() a bit

.github/workflows/test.yml, roboflow/core/version.py
Github actions were not being run after renaming the base branch from `master` to `main`. This should fix that.
I opened this PR and saw that the actions are working again.
=> Switch github action target branch from master to main

README.md, roboflow/config.py, roboflow/core/project.py, setup.py, tests/__init__.py
Batch name was a parameter added to the upload api which allows users to specify a specific bucket to upload to. See batch upload info in docs (pending push).
We did not make a test / unit case file, but we tested the following edge cases:
- batch name not specified, `project.upload("test.jpg")`
- batch name with empty string provided, `project.upload("test.jpg", batch_name="")`
- batch name with None, `project.upload("test.jpg", batch_name=None)`
- batch name with number, `project.upload("test.jpg", batch_name=1)`
will need to update the docs pip package section.
- …
=> Batch name upload

requirements.txt, setup.py
I've noticed that on certain versions of  `python` in my case `3.10.7` kiwisolver build was failing as it required C++ 14.0 or greater build tools, that is unacceptable as this should be a simple install. So I've relaxed the kiwisolver dependencies a bit. 
`kiwisolver>=1.3.1` (instead of kiwisolver==1.3.1)
-   [ x ] Bug fix (non-breaking change which fixes an issue)
Relaxed kiwisolver would help ease install for Windows users. 
YOUR_ANSWER
None
=> kiwisolver support for Python 3.10.x and other versions relaxed.

README.md, roboflow/core/workspace.py, roboflow/util/clip_compare_utils.py, setup.py
Given a `dir` of images and a `target` image, perform CLIP encoding and similarity comparison using our hosted CLIP backend (uses cosine similarity method) and returns an object mapping each image's similarity score from the `dir` to the `target` image. 
No required dependencies that weren't already in there. I added `twine` to the list of `dev` packages as we use twine to update the hosted package up in the pypi store.
You must specify the following URL in `config.py` as the env variable `CLIP_FEATURIZE_URL`, `'https://clip-featurize-double-image-li37nwjfaq-uc.a.run.app/predict'`, to hit the endpoint as this endpoint does not have auth / usage tracking.
-   [x] New feature …
=> Clip compare

roboflow/core/workspace.py
Users were previously required to use all conditions for active learning so added edge case handling to the `conditionals` object in case users don't specify all possible key words.
Ran a series of unit tests with the below code snippet making sure all variations were supported including no config object, one field, all fields, some fields, `value == None`, etc.
```
rf = Roboflow(api_key="BLlkFnwfSaRFUXBfU0tJ")
upload_conditions_config = {
"target_classes": ['helmet'],
"confidence_interval": [30,90]
} …
```
=> added edge case handling for conditional object

roboflow/models/object_detection.py
We added cv2 to our package list because we want to use it for image encoding. This allows us to bypass saving an image locally and might save inference time.
I added some logic to fix when an end user tried to send an OpenCV frame array. Previously the logic would crash and we provided a statement to ensure that doesn't happen for frame array data.
import cv2
Tested on multiple webcam and resolutions.
Still passes images paths and image URLs just fine.
Not sure the size of the cv2 package, but it is something to consider. Probably worth storage space if it speeds up inference logic.
-   [ ] Docs updated? 
What …
=> OpenCV Image Encoder

roboflow/core/project.py, roboflow/core/workspace.py, setup.py
Updated `Version` so users can specify a locally running inference server within the pip package.
Test code:
```
rf = Roboflow(api_key="BLlkFnwfSaRFUXBfU0tJ")
model_name = "hard-hat-universe-0dy7t"
model_number = 17
upload_img_directory = "./"
image_extention_type = ".png"
project_upload_destation = "merge_tester"
conditionals = {
"required_objects_count" : 1,
"required_class_count": 1,
"target_classes": [],
"minimum_size_requirement" : float('-inf'),
"maximum_size_requirement" : float('inf'),
"confidence_interval" : [10,90],
} …
```
=> Local active learning

roboflow/config.py, roboflow/models/object_detection.py, roboflow/util/clip_compare_utils.py, tests/__init__.py, tests/models/test_instance_segmentation.py, tests/models/test_object_detection.py, tests/models/test_semantic_segmentation.py, tests/test_project.py, tests/test_queries.py, tests/test_version.py, tests/util/test_image_utils.py
Added checks for `image_path` type in `model.predict`, it can be either `str` or `np.array`. If it's a `str` we will use `PIL` to open it, otherwise `cv2.imencode` 
`PIL` will raise a `PIL.UnidentifiedImageError` error if it cannot load the image, e.g. sending a text file `photo.asd` returns in 
```
PIL.UnidentifiedImageError: cannot identify image file 'photo.asd'
```
Linked to #83 
YOUR_ANSWER
=> removed check for extensions, PIL will do that for us

roboflow/core/version.py
New format alias for `yolov8` needs the same treatment as `yolov5` and `yolov7`.
Locally
Deploy to pip
- Not needed
=> Update YAML for YOLOv8

roboflow/__init__.py, roboflow/core/version.py
This change adds a dataset download overwrite flag. By default, it is set to `True` to keep the current default behavior. When set to `False,` the dataset won't get downloaded if it is already available locally. 
The motivation for that change is my current work on [PR](https://github.com/ultralytics/ultralytics/pull/295) to YOLOv8. The code there is structured so that it would re-download the dataset multiple times.
I can change the docs if we already have documentation for that method somwhare.
=> add dataset download overwrite flag

roboflow/__init__.py, roboflow/core/version.py
Support old versions of Ultralytics YOLOv8 deploy - they changed the class types of their model args, but we may still want to parse those older models
=> Support Old Versions of Ultralytics YOLOv8 Deploy

roboflow/core/version.py
Our `.deploy()` method currently works only if `model_path` is a string with `/` at the end. That results in unintuitive behavior. This PR makes the deployment work regardless of having `/` at the end or not.
https://github.com/roboflow/notebooks/issues/51#issue-1554182751
=> Fix problems related to lack of trailing / at the end of model_path.

roboflow/util/versions.py, tests/util/test_versions.py
The current way I was converting to a version to a number was 
```
int(x.replace(".", ""))
```
this is not correct, if we have two version `0.2.0` and `0.1.34`, they will be converted to `20` and `134` respectively creating an issue. 
I've switched to the built-in `packaging.version` package to parse the version number
=> Fix an error in depedencies' version parsing

roboflow/core/version.py
If `ultralytics` is not installed in `version.download`, the `print_warn_for_wrong_dependencies_versions` will throw an `ImportError`, since there are no `ultralytics` modules.
We now catch it and `pass` without printing anything. This makes sense because if the user tries to use `.deploy` later, we will inform him he needs to have `ultralytics` installed. 
I could also print a warning instead of `pass` it, down for suggestions
=> Silently fail to print the warning in version.download if Ultralytics not installed

roboflow/__init__.py, roboflow/core/version.py, roboflow/util/annotations.py, roboflow/util/versions.py
PR solves problems related to https://github.com/ultralytics/ultralytics/issues/873. Along with the `8.0.30` release, the YOLOv8 team changed the dataset loader default behavior. Currently, or dataset does not work with any `ultralytics` version higher than `8.0.29`.
After downloading we detect that the currently installed version of `ultralytics` is higher than `8.0.29` and amend `data.yaml`
```
test: test/images
train: train/images
val: valid/images
```
- In short, on Feb 6th YOLOv8 team released version `8.0.30` (here is the whole [diff](https://github.com/ultralytics/ultralytics/pull/832/files#diff-15f6dd1ea95b187a5b50c885f567bad50d006f1af1180508497a038247e9df58)) and that broke integration between Roboflow datasets and training and validation code. 
- There is [one …
=> 🧪 ready for colab tests

roboflow/__init__.py, roboflow/core/project.py
Updated annotation upload logic to support passing a class name as a raw string to classification projects.
test cases:
- empty string
- string is filepath that doesn't exist
- string is alphabet characters
For some reason using a number in a string such as `"1"` fails on upload and not sure why. Will need separate resolution.
-   [x] Docs updated? What were the changes: need to update docs to support classification string
=> Classification annotation upload

roboflow/core/project.py
Referenced `self.name` instead of `self.__project_name`. During original testing these coincidently were the same but can sometimes differ when we do string sanitation.
=> update annotation upload to reference correct project name

roboflow/__init__.py, roboflow/models/classification.py
Had to add image_dims to the return statement for classification inference. The PredictionGroup requires that parameter and I would rather not delete it as it might be a legacy / active para in the PredictionGroup function.
Easiest fix was to add image.size to the classification predict function and pass that in the return to maintain the next function.
Tested on multiple two stage scripts. Confirmed that it does fix the classification inference issue.
There is no change to the docs necessary and the call method will stay the same.
=> Classification Inference Fix - PredictionGroup

Makefile, roboflow/__init__.py
Removes TestPyPi from Publish Action as we often do that manually ahead of time
=> Removes TestPyPi from Publish Action

roboflow/core/version.py
Added `nocache=true` query param to the model upload api call to ensure we have the latest data for the model version.
=> `nocache=true` for Model Upload API

roboflow/__init__.py, roboflow/core/version.py, roboflow/models/object_detection.py
This moves and renames a single method, as a follow-up of #137 
`Version.get_pt_weights` is replaced by `model.download()`, which makes more sense: download a model's weights is an operation that should belong to the model (version already has a `download()` method to download images)
Tested locally against the production api
=> Pt download2

roboflow/core/project.py
The annotation upload API has a new parameter to mark whether the uploaded annotation data is a prediction rather than ground truth.
When annotation data is uploaded as a prediction, the image is kept in the batch or existing job it is in rather than being added directly to the dataset as an annotated image.  Using this parameter user can add annotation data but keep the image in the regular annotation flow for further review/adjustment of the annotations (e.g. for active learning workflows).
Could use some help testing this, I just put the code/parameters where I thought they needed to go for now.
=> add `is_prediction` parameter to upload functions

roboflow/__init__.py, roboflow/core/version.py, roboflow/models/instance_segmentation.py
Added the `local` parameter functionality to instance segmentation giving the ability to infer using a local inference server instead of the hosted endpoint.
Tested locally with dev script
=> `local` Parameter For Instance Segmentation Version

roboflow/__init__.py, roboflow/core/project.py
This PR introduces two new methods:
- `search`: Returns the search results for a dataset search query.
- `search_all`: Returns a generator that yields pages of search results. 
You can test this feature using the following code:
```
roboflow.login()
rf = roboflow.Roboflow()
workspace = rf.workspace()
project = rf.project("mug-detector-23eqf")
print(project.search(
prompt="mug"
))
records = []
for page in project.search_all(
prompt="mug"
):
records.extend(page)
print(len(records))
```
You will need to specify your own dataset ID.
N/A
I will update our quickstart docs on Gitbook once we release this feature.
=> Add search and search_all attributes

roboflow/__init__.py, roboflow/core/version.py
Corrects logging for the model upload feature. 
- Required ultralytics version is > 8.0.20 rather than <
- Deploy page URL is updated to correct path
Previous logs asked for ultralytics version < 8.0.20, even though we require a greater version. And they point to the old URL path of `../deploy/..`
New logs point to correct path
Tested model upload with local package.
None.
=> Bugfix/ Model upload logs

roboflow/__init__.py, roboflow/core/project.py, roboflow/core/workspace.py, roboflow/util/general.py
Fixes #163 
The upload API may sometimes have some hiccups giving 502 errors with some html in the response.
The pip package handles errors, but doing `response.json()` when handling an error will itself throw an error, and that can break uploading a big dataset.
This PR makes uploading more robust when using `workspace.upload_dataset`
Uploaded big dataset using a snippet like
**testupload.py** 
```python
#! /Users/tony/.pyenv/shims/python
rf = Roboflow()
workspace = rf.workspace("tonyprivate2")
dataset_path = '/Users/tony/Downloads/ppe.voc'
workspace.upload_dataset(dataset_path=dataset_path, num_workers=10, project_name="ppe", dataset_format="voc")
```
Obs: if you separate stdout from stderr with …
=> Make uploading large datasets more robust

roboflow/__init__.py, roboflow/core/project.py
Uploading annotations takes an optional parameter `is_prediction`, which had an innocuos effect as it was being passed with the wrong name to the actual backend API
Tested locally
context - https://roboflow.slack.com/archives/C02KWK9U8PQ/p1692816353862449?thread_ts=1692756384.477109&cid=C02KWK9U8PQ
Will need a new release
=> fix prediction parameter name

CHANGELOG.md, CITATION.cff, README.md, docs/core/dataset.md, docs/core/model.md, docs/core/project.md, docs/core/version.md, docs/core/workspace.md, docs/index.md, docs/models/classification.md, docs/models/instance-segmentation.md, docs/models/object-detection.md, docs/models/semantic-segmentation.md, docs/styles.css, mkdocs.yml, roboflow/core/dataset.py, roboflow/core/model.py, roboflow/core/project.py, roboflow/core/version.py, roboflow/core/workspace.py, roboflow/models/classification.py, roboflow/models/inference.py, roboflow/models/instance_segmentation.py, roboflow/models/object_detection.py, roboflow/models/semantic_segmentation.py, setup.py
This PR adds Pythonic documentation to the `roboflow-python` package.
In this PR, I have:
- Reformatted docstrings in the main package (everything other than `util`) to ensure they are consistent.
- Added new docstrings where required.
- Removed informal language from docstrings.
- Added type hints across the main package (although there may be more left to add).
- Added documentation powered by `mkdocs` for use by package developers. There is no way to see all of the Python methods available without digging into the source code right now.
- Updated the quickstart in the README.
This PR does not include any functoinality changes.
To test this change, install `mkdocs` then run `mkdocs serve` in the main project directory.
James will need to run `mkdocs gh-deploy` to deploy the docs.
=> Add Pythonic documentation

requirements.txt, roboflow/core/version.py, roboflow/models/object_detection.py
This PR removes the `wget` dependency from `roboflow-python` and replaces its use with `requests`. This change affects downloading model weights and datasets from Roboflow. Both the dataset download and weight export should be tested to validate this change.
Also `requests.exceptions.JSONDecodeError` is deprecated and has been replaced with `json.JSONDecodeError`.
`pytest` was run to validate that all tests pass.
N/A
N/A
=> Remove `wget` dependency and fix `JSONDecodeError` import

requirements.txt, roboflow/__init__.py, roboflow/config.py, setup.py
This PR uses the `os.path.join()` method for path resolution instead of manual concatenation of paths for generating the full path of the Roboflow config file. This will fix #136.
=> Update config path resolution

requirements.txt, setup.py
This PR creates a new `roboflow[desktop]` installation method and removed `opencv-python` as a required dependency for `roboflow`. Instead, `roboflow` will use the lighter `opencv-python-headless`, and `roboflow[desktop]` will use `opencv-python`.
=> Create `roboflow[desktop]` installation method

roboflow/__init__.py, roboflow/core/version.py, roboflow/util/versions.py
Adds input warning that requires `y` input to continue with wrong package version. Introduces this to the ultralytics version check in the version `deploy` method. This will help resolve some model upload compatibility issues.
=> Add input continue warning for wrong ultralytics version in model deploy

.github/workflows/test.yml, .vscode/settings.json, docs/index.md, roboflow/__init__.py, setup.py
Updated python version requirements to >=3.8 from 3.6 in setup.py and Readme. Python 3.8 is now the earliest version Roboflow supports because it’s the earliest version supported by our dependencies. Here’s [the discussion](https://github.com/roboflow/supervision/pull/180) from when supervision dropped support for 3.7 a few months ago.
-   [X] This change requires a documentation update
=> python version to >=3.8 from 3.6 in setup.py and readme

roboflow/__init__.py
This PR increases the `roboflow-python` version to 1.1.18.
This release contains code tested in all individual accepted PRs since the last release.
I will need @tonylampada's help publishing the change.
N/A
=> Increase version to 1.1.8

roboflow/__init__.py, roboflow/models/inference.py
We were not adding fine-tuned models; this PR adds those.
YOUR_ANSWER
=> Add finetuned models

roboflow/models/inference.py, roboflow/models/video.py
This PR updates the video inference API wrappers in the `roboflow` package to adhere to the `fps` that the user passes.
This change can be tested using the following code:
```python
rf = Roboflow(api_key="API_KEY")
project = rf.workspace().project("logistics-sz9jr")
model = project.version(2).model
job_id, signed_url = model.predict_video(
"video.mp4",
fps=1,
prediction_type="batch-video",
)
results = model.poll_until_video_results(job_id)
print(results)
job_id, signed_url = model.predict_video(
"video.mp4",
fps=5,
prediction_type="batch-video",
)
results = model.poll_until_video_results(job_id)
print(results)
```
And ensuring that the FPS intervals are 1 FPS for the first video and 5 fps for …
=> Allow video inference `fps` value to pass through to API

README.md, roboflow/__init__.py, roboflow/models/inference.py
-Removed 5 fps limit for video inference API
-Updated Readme to specify python >=3.8
-   [ X] This change requires a documentation update
=> Remove FPS limit

CLI-COMMANDS.md, Makefile, README.md, pyproject.toml, roboflow/__init__.py, roboflow/adapters/rfapi.py, roboflow/config.py, roboflow/core/project.py, roboflow/core/version.py, roboflow/core/workspace.py, roboflow/models/__init__.py, roboflow/models/classification.py, roboflow/models/inference.py, roboflow/models/instance_segmentation.py, roboflow/models/object_detection.py, roboflow/models/video.py, roboflow/roboflowpy.py, roboflow/util/active_learning_utils.py, roboflow/util/prediction.py, roboflow/util/versions.py, tests/manual/debugme.py, tests/test_project.py, tests/test_queries.py, tests/test_version.py
It's not ideally efficient for our users to need to install [roboflow-python](https://pypi.org/project/roboflow/) AND [roboflow-cli](https://www.npmjs.com/package/roboflow-cli) to do similar things.
It's also not ideal for us to need to maintain both ;-)
This PR adds more subcommands to the python version of the `roboflow` command:
* list workspaces and projects
* get details for workspaces and projects
* run inference
The commands are documented in [this new markdown file](https://github.com/roboflow/roboflow-python/blob/newcommands/CLI-COMMANDS.md) (and there's a reference to it in the main README)
It also fixes a bug with the authentication mechanism: if the user had authenticated for multiple workspaces, it would only use the API_KEY for the default workspace, and the authentication …
=> Add new commands to the CLI

requirements.txt, roboflow/__init__.py
We have `pyparsing==2.4.7` pinned to our requirements.txt, which we shouldn't need because it's already brought in by matplotlib. This minimizes the risk of dependency problems when installing roboflow together with other packages.
- Tests still pass
- We are testing some installing configurations on google colab
=> no need to pin pyparsing

roboflow/core/version.py
This PR changes the `download()` method to set the `overwrite` flag to `False` by default. This will ensure that a dataset is not re-downloaded every time the `download()` method is run.
This addresses #108.
Run the following snippet twice:
```python
!pip install roboflow
rf = Roboflow(api_key="")
project = rf.workspace("capjamesg").project("streamlit-logo-detection")
dataset = project.version(1).download("coco")
```
When you run the code for the first time, a `Downloading Dataset Version Zip in` message should appear as the dataset is downloaded. On the second run, `Downloading Dataset Version Zip in` should not appear.
N/A
N/A
=> Change `download()` to not overwrite files by default

roboflow/adapters/rfapi.py, roboflow/core/project.py
Added a new parameter for the single_upload method to enable overwriting annotations via the API. This has been requested by multiple other users. The option was available via the REST API, but not the python SDK.
Tested upload of image with annotations then deleted part of the annotations manually, and re-uploaded only the annotations.
One of the unittests was already broken on the main branch (`test_download_returns_dataset` in `tests.test_version`. I did not touch this.
-   [ ] Docs updated? What were the changes: No changes made to docs.
=> new upload parameter for overwriting annotations

roboflow/models/object_detection.py
Fixes the following error:
```
>>> model.download()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/avaishampayan/projects/petra-ai/libs/rivian-petra-ml/.venv/lib/python3.10/site-packages/roboflow/models/object_detection.py", line 503, in download
for chunk in tqdm(
TypeError: 'module' object is not callable
```
Tested Locally
n/a
n/a
=> fix tqdm import for download progress

roboflow/__init__.py, roboflow/adapters/rfapi.py, roboflow/core/project.py, roboflow/core/workspace.py, roboflow/util/folderparser.py, tests/manual/debugme.py
The upload image endpoint has input parameters `sequence_order` and `sequence_size` that allows the client to control the parameter used to sort images in the backend.
This PR: 
* Exposes that as new parameters in `project.single_upload` method
* Automatically uses that in `workspace.upload_dataset` so that files are saved in the alphanumerical order they are found in the filesystem (instead of a random order).
So now if you run 
`$ roboflow import path/to/dataset/` 
you get something like this:
Tested by uploading it to staging from roboflow-python dev environment
Will release version 1.1.18
=> ordered-uploading

README.md, docs/index.md
`upload_dataset` is a function of `workspace` - not `project`.
Code line in `workspace`: https://github.com/roboflow/roboflow-python/blob/ef6e3d9b32c8503fe2bfa7583e7ee8ba169b9214/roboflow/core/workspace.py#L271
Project: https://github.com/roboflow/roboflow-python/blob/main/roboflow/core/project.py
None.
-   [x] Docs updated? What were the changes:
Tiny updates to `Readme.md` and `index.md`.
=> Readme: upload_dataset in workspace, not project

roboflow/core/project.py
This seems like a miniscule change, but it it would have saved me 2 hours today.
It took time to create a COCO annotations file, only to find that:
* RF API fails silently when you send a file with an incorrect format, without feedback as to what's wrong
* The parameter allows sending of the class label directly.
None
This only changes the docstring.
N/A
~~I got `mkdocs serve` running, but could not locate any `Project` docstring renderings.
If that is displayed somewhere, it should be checked that parameters of …
=> Clarified `annotations_path`, `split params` in `project.upload`.

roboflow/__init__.py, roboflow/core/project.py, roboflow/core/workspace.py, roboflow/roboflowpy.py, roboflow/util/folderparser.py, roboflow/util/general.py, tests/__init__.py, tests/models/test_object_detection.py
After troubleshooting a clients uploading problems, I'm making this PR with two incremental QoL features:
* Adds `-r retry` parameter to `roboflow import` CLI command. This controls how many times the CLI may retry a failed upload  before giving up. This is important because sometimes the API will reply with a 503 (GCP is the culprit and there's not much we can do except for retrying)
* Adds the actual number of retry attemps to each line log. Which is useful when we see "DUPLICATE" log entries for images that are not really dupes (the cause here is that, we got an error from the API but the upload went through, so the second call returns falsely flagged as duplicate)
* When uploading coco datasets, if the image has 0 annotations, the annotation json is not recognized as a valid …
=> Reliability improvement for CLI upload

roboflow/__init__.py, roboflow/adapters/rfapi.py
This adds a large timeout to uploads (5min for images, 1min for annotations).
When uploading datasets with lots and lots of images, this will make sure that uploader workers don't get stuck forever on bad http calls.
I was able to upload full COCO dataset with the CLI after this change
-   [x] Reliability improvement
I was able to upload full COCO dataset with the CLI after this change
=> Individual Upload timeouts

roboflow/__init__.py, roboflow/util/folderparser.py, tests/util/test_folderparser.py
Fixes [roboflow-bugtracker#908](https://github.com/roboflow/roboflow-bugtracker/issues/908)
Two dictionaries were added to speed up the search for images and annotations rather than iterating through a list to find matches. 
Along with that a tqdm loading bar was added to the image loop to give users feedback during the parsing of their annotation/image folder. 
All existing tests under `tests/util/test_folderparser.py` are passing after this work. 
An inital stub test below was implemented to test speed improvements on the CocoNut Datset. 
if you have the coconut dataset, it can be passed to the dev container with the following …
=> bugfix: CLI hangs with super big dataset

CONTRIBUTING.md
CONTRIBUTING.md now has sections.
Added instructions:
* How to rebuild the dev container
* How to serve the docs (unsure if there's a better way)
Opening a draft PR - let me know if there's a better way to install the dependencies for docs.
-   [x] This change requires a documentation update
1. I rebuilt the container, ran the doc dependency install command I added, served the docs.
2. I checked that contributing.md looks okay in the repo.
Is this the best way of installing `mkdocs` dependencies?
-   [x] Docs updated? What were the changes:
CONTRIBUTING.md:
* How to rebuild the dev container
* How to serve the docs (unsure if there's a better way)
=> CONTRIBUTING.md: sections, mkdocs serve, container rebuild

roboflow/config.py, roboflow/core/version.py
Add the option to quieten TQDM messages.
Set the environment variable TQDM_DISABLE=1 if you don't want the download/unzipping  progress-bars
Testing in progress...will update here
=> Added an environment variable to silence TQDM output

roboflow/__init__.py, roboflow/core/version.py
Cherry picked one commit that @SolomonLake  authored that adds yolov10 model upload support
Locally/staging
no
=> Add support for yolov10 model deploy

requirements.txt
We try to install a yanked version. Some installers fail because of that.
https://pypi.org/project/opencv-python-headless/#history
CI pass
=> Bump `opencv-python-headless` yanked version

.github/workflows/test.yml, pyproject.toml, setup.py
Ref #263
We have many types defined in this project, but we don't have type checking.
[CI reports many errors](https://github.com/roboflow/roboflow-python/actions/runs/9612810927/job/26514215586#step:7:12). For now, it is ignoring errors, but the long term plan should be to fix all these errors and enforce typing on CI.
=> Setup mypy

.github/workflows/test.yml, pyproject.toml, roboflow/adapters/rfapi.py, roboflow/core/project.py, roboflow/core/version.py, roboflow/core/workspace.py, roboflow/models/classification.py, roboflow/models/inference.py, roboflow/models/instance_segmentation.py, roboflow/models/keypoint_detection.py, roboflow/models/video.py, roboflow/util/prediction.py, setup.py
Fix more mypy errors.
Checked mypy errors.
=> Fix many mypy errors

roboflow/models/gaze.py
Fix #269.
The superclass expect a `version_id`. I'm kind of breaking backward compatibility because the class is broken anyway.
Mypy like it.
=> Fix `GazeModel` init

roboflow/core/version.py
Allow deploy of florence2 models
staging/prod
nope!
=> Allow florence2 deploys

roboflow/adapters/rfapi.py, tests/test_rfapi.py
Fix #263 
- Coalesces the value of `batch_name` used to build the image url to use the `DEFAULT_BATCH_NAME` when `None`.
Unit tests
=> Fixes batches being created with `None` name

roboflow/core/version.py
Fix errors found after mypy merge.
```
roboflow/core/version.py:110: error: Unsupported operand types for in ("str" and "Response")  [operator]
roboflow/core/version.py:110: error: Value of type "Response" is not indexable  [index]
```
It was a small bug that would be triggered only when our API failed.
Minor regression from https://github.com/roboflow/roboflow-python/pull/276.
CI pass.
=> Fix types in version init

roboflow/__init__.py, roboflow/core/project.py
Fix an image path issue that occurs when specifying a directory of images to upload.
Tested locally.
- pip package
=> Use correct image path when validating during image directory upload

pyproject.toml, requirements.txt, roboflow/core/project.py, roboflow/models/video.py
* Add support for BMP and WEBP images.
* Add support for AVI video, mimetype was wrong.
* Add warn for file mimetype does not match filename extension.
* Replace `magic` dependency (and `libmagic` system dependency) with `filetype` that is pure Python.
CI pass.
=> Add warning for mismatched mimetype and filename extension

roboflow/__init__.py, roboflow/core/project.py, roboflow/core/version.py, roboflow/core/workspace.py, roboflow/roboflowpy.py
api key reverted to roboflow.config demo key / api key even if initializing roboflow workspace with api key. now initializing api key takes precedence
-   [ X] Bug fix (non-breaking change which fixes an issue)
CI tests + custom test with roboflowpy.py get_workspace_project_version()
=> api key precedence

roboflow/core/workspace.py
Some users utilize the active learning code via the Python package. The inference server address is hardcoded to 'http://localhost:9001/'. These charges allow the user to pass in a different server address, other than localhost.
-   [ x] Bug fix (non-breaking change which fixes an issue)
Tested by using active learning function to upload images to Roboflow project using a local server not at localhost. 
No changes.
=> Active Learning - Ability to change inference server path.

roboflow/core/version.py
Raise runtime error if the model type isnt supported by roboflow-model-conversion
Locally
=> Warn users about correct model type string for hf uploads

pyproject.toml, roboflow/core/version.py, roboflow/core/workspace.py, roboflow/models/object_detection.py, roboflow/util/image_utils.py, roboflow/util/prediction.py, tests/models/test_object_detection.py
Ban some big global imports to make it faster to `import roboflow`. It makes initial import ~3x faster.
[Benchmark](https://colab.research.google.com/drive/12bXEnQljCl47gDhQbJmSxNkS8gQp0v0C?usp=sharing)
=> Ban module level imports for `cv2`, `matplotlib` and `numpy`

roboflow/__init__.py, setup.py
Fixes login bug (`os.mkdir can only create directory if parent dir already exists`)
Tested locally
=> bugfix: login breaks if ~/.config doesn't exist

requirements.txt
Removes chardet dependency.
* not used by our code
* doesn't show up as a dependency of anything in [pipdeptree](https://pypi.org/project/pipdeptree/)
* tests pass without it
* command line still seems to work
* git history does not provide a clear reason for why it was added
-   [x] Maintainability
* Tests passing
* Used the CLI locally
No need to release because of this
=> chardet is not required for anything

roboflow/__init__.py, roboflow/models/inference.py, roboflow/models/video.py, roboflow/roboflowpy.py, tests/manual/video_inference.sh
Ensure FPS limit of 120 is consistently enforced
-   [X ] Bug fix (non-breaking change which fixes an issue)
Passed tests
=> ensure fps limit of 120 enforced

roboflow/core/project.py
Fixes issue #235 by raising `UploadError` exceptions that happens inside `single_upload`
Same test as the issue
```
import json
rf = roboflow.Roboflow(api_key="API_KEY")
img_path = "<path_to_img>"
workspace_id = "<ws ID>"
project_id = "<proj ID>"
workspace = rf.workspace(workspace_id)
project = workspace.project(project_id)
annotation = {
"it is": [
{
"very frustrating": 0,
"when you": "send",
"an annotation": {
"file and": 0.5,
"function": 0.5,
"call": 0.5,
"completes": 0.5,
"successfully,": 0.5,
},
"but": "there's",
"no": "annotations",
"on": "the website",
"nor": "any",
"errors": "raised",
}
]
}
with open("annotation.json", "w") as f:
json.dump(annotation, f)
image = …
```
=> fix: raise UploadErrors for images and annotations

roboflow/models/inference.py
If user provides a `job_id` when call `poll_for_video_results`, we should use that id instead of `self.job_id`
YOUR_ANSWER
=> poll video inference job: use job_id if provided

README.md, roboflow/__init__.py, roboflow/core/version.py
Below results in error:
```bash
python3.9 -m venv venv
source venv/bin/activate
pip install -e .
```
```python
rf = roboflow.Roboflow(api_key="<redacted>")
workspace = rf.workspace(the_workspace="<my workspace ID>")
proj = workspace.project(project_id="<my prioject ID>")
version = proj.version(1)
version.deploy(
model_type="yolov10",
model_path="/path/to/my_yolov10_dir",
filename="my_model.pt",
)
```
Above results in following exception:
```python
Traceback (most recent call last):
File "/path/to/my_script.py", line 10, in <module>
version.deploy(
File "/path/to/roboflow-python/roboflow/core/version.py", line 522, in deploy
model = torch.load(os.path.join(model_path, filename))
File "/path/to/roboflow-python/venv/lib/python3.9/site-packages/ultralytics/utils/patches.py", …
```
=> Fix yolov10 version deploy

roboflow/__init__.py, roboflow/core/project.py
- Add multilabel field
- fix doc error
- bump version number
Will be tested in staging in model_eval
=> Feat: Multi-label support

roboflow/core/version.py
Please include a summary of the change and which issue is fixed or implemented. Please also include relevant motivation and context (e.g. links, docs, tickets etc.).
Related to this issue https://github.com/roboflow/roboflow-python/issues/311.
I debugged by outputting the contents of epoch here https://github.com/roboflow/roboflow-python/blob/main/roboflow/core/version.py#L414
Somehow for the last epoch , we do not find the "loss" values .  (It shows up in UI though, but somehow not in this dict).
Here is the output from my debugging. Please refer the last epoch 167
```
epoch in for loop {'recall': 0.5, 'mAP': 0.0072, 'obj_loss': 2.61305, 'ts': 1724181787.4027717, 'box_loss': 3.15483, 'mAP_50_95': 0.00203, 'class_loss': 3.7698, …
```
=> fix_box_loss_error

roboflow/core/version.py
Fixes bug introduced here: https://github.com/roboflow/roboflow-python/pull/279/files, where `has_model` is always false for models uploaded to Roboflow. Those models will not have a "models" field on their version record.
Tested locally with uploaded model, and model trained with roboflow.
no
=> Fix check for has_model for model upload

roboflow/core/version.py
Please include a summary of the change and which issue is fixed or implemented. Please also include relevant motivation and context (e.g. links, docs, tickets etc.).
Fixes this issue 
https://github.com/roboflow/roboflow-python/issues/314
Steps to reproduce
From the UI, Created a new project, new version with sample dataset, created version.
Ran the training code.
```
workspace = rf.workspace()
project = workspace.project('test2-forest-fire-detection')
version = project.version(6)
print ('version',version)
version.train()
```
Getting error
```
Traceback (most recent call last):
File "/Users/venkat/Documents/robo_python_trial/r_train.py", line 13, in <module>
version.train()
File "/Users/venkat/Documents/robo_python_trial/rvenv/lib/python3.12/site-packages/roboflow/core/version.py", line …
```
=> fix_assert_model_version

.gitignore, roboflow/__init__.py, roboflow/core/version.py, tests/manual/debugme.py
Our train notebooks like [train-yolov8-object-detection-on-custom-dataset.ipynb](https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/train-yolov8-object-detection-on-custom-dataset.ipynb) are having to do weird yaml amending like
When you export a dataset in yolov8 format from the UI, you get a correct yaml that has
```yaml
train: ../train/images
val: ../valid/images
test: ../test/images
```
But if download it with roboflow-python you get a modified yaml like
```yaml
test: ../test/images
train: football-players-detection-12/train/images
val: football-players-detection-12/valid/images
```
It's not good that the train notebook needs to undo the mistake of roboflow-python
This PR fixes that mistake.
-   [x] Bug fix …
=> bugfix - downloading yolov8 files incorrectly amends data.yaml

roboflow/adapters/deploymentapi.py, roboflow/deployment.py
Add log support for dedicated deployment.
Tested locally.
=> Add log support for dedicated deployment

roboflow/core/project.py
There are cases in which the `project.created` or `project.updated` values are `null`. Project initialization should not fail even if the timestamps are null. This change allows null timestamps
Tested locally. Any project initialization tests this change
=> Allow null "updated" or "created" timestamps

roboflow/core/project.py
Reverts roboflow/roboflow-python#338
It was a hotfix to not break with `updated == null`, but we already fixed the root cause.
It is not good to keep these checks because we'll never trust we can safely remove them in the future.
=> Revert "Allow null "updated" or "created" timestamps"

roboflow/adapters/deploymentapi.py, roboflow/deployment.py
Add feature for querying dedicated deployment usage:
all deployments in a workspace: `roboflow deployment usage_workspace [from_timestamp] [to_timestamp]`
a specific active deployment: `roboflow deployment usage_deployment deployment_name [from_timestamp] [to_timestamp]`
Tested locally
=> Add feature for querying dedicated deployment usage (per workspace)

roboflow/adapters/deploymentapi.py, roboflow/deployment.py
Use local timezone when query logs & usages for dedicated deployment, default is UTC time.
Tested locally.
=> Use local timezone when query logs & usages for dedicated deployment

CHANGELOG.md, roboflow/__init__.py, roboflow/core/version.py, roboflow/deployment.py
PaliGemma2 model upload support
- Locally
?
=> PaliGemma2 model upload support

roboflow/__init__.py, roboflow/adapters/rfapi.py, roboflow/core/project.py, roboflow/core/version.py, roboflow/core/workspace.py, roboflow/deployment.py, roboflow/models/object_detection.py, roboflow/roboflowpy.py, roboflow/util/versions.py
Only perform a optimizing "stretch" resize if that is the resize format. Without this fix it will produce incorrect predictions for resize formats such as "Fit within". 
Tested locally with the python package.
none
=> Only stretch image to resize if format is Stretch

roboflow/__init__.py, roboflow/core/version.py, roboflow/core/workspace.py, roboflow/roboflowpy.py, roboflow/util/model_processor.py
- Created `model_processor.py` which processes and zips models before uploading.
- Moved the processing responsibility from `version.py` to `model_processor.py`.
- Added the `-f` flag to the `login` command to force re-login, even if already logged in.
- Locally pointing to staging
=> Model processor

roboflow/__init__.py, roboflow/core/workspace.py, roboflow/roboflowpy.py
You can now deploy versions without specifying the version number. To do this, you can use the deploy_model method from the Workspace:
Example:
```
workspace.deploy_model(
model_type="yolov8",
model_path="/path/to/model",
model_name="my-model123"
project_ids=["project1", "project2", "project3"],
filename="weights/best.pt"
)
```
Alternatively, you can use the CLI:
```
roboflow upload_model -p project1 -v 1 ...
roboflow upload_model -p project1 -p project2 -p project3 -n my-model123 ...
```
- I tested it locally using the CLI and the Python package, both pointing to the staging environment with the changes introduced in the PR [#5188](https://github.com/roboflow/roboflow/pull/5188)
=> Versionless model deploy/upload

roboflow/__init__.py, roboflow/core/project.py, roboflow/core/version.py, roboflow/deployment.py, tests/test_project.py
This PR adds support for the Image Details endpoint on the API to the Python SDK: https://docs.roboflow.com/api-reference/images/image-details
Example:
```
rf = roboflow.Roboflow(api_key="YOUR_API_KEY")
project = rf.workspace().project("PROJECT_ID")
image_details = project.image("image-id")
```
Also adds tests
Tested locally + externally here: https://colab.research.google.com/drive/1PMUgiSA-S-OO6F1I_k27Me282_aeJyEO?usp=sharing
Test added and ran
=> Add support for the Image Details endpoint

roboflow/__init__.py, roboflow/adapters/rfapi.py, roboflow/core/project.py, roboflow/core/workspace.py, roboflow/util/general.py
We're not retrying because we're not handling the `-r` arg. It's broken since [PR](https://github.com/roboflow/roboflow-python/pull/312/files#diff-0eb0f71fe42476c760528a9097aa391dd0d5490d1e2d36facc90bf4cad0beb3eL364).
This PR:
* Pass `num_retries` downstream to retry on errors
* Add retry on annotation upload errors
* Add backoff and jitter to our retry strategy
I tested `import` command in staging, but hard to test for failures.
=> Fix retry arg and improve retry strategy

roboflow/core/project.py, tests/test_project.py
This PR adds a method onto the `Project` class for creating an annotation job that is assigned to specific users.
Added unit tests and verified the HTTP request against the endpoint.
N/A
We would need to update this page: https://docs.roboflow.com/api-reference/annotation-jobs
=> Add a project method for creating annotation jobs

roboflow/__init__.py, roboflow/core/workspace.py
Fixes bug introduced by: https://github.com/roboflow/roboflow-python/pull/362
locally
n/a
=> Fix number of returns

roboflow/core/workspace.py, tests/test_project.py
This PR fixes a user-reported bug that occurs when uploading a dataset - sometimes, annotation data is an empty string for an image and causes uploads to fail with the following error:
> [ERR] grain-multi/datasets/train/images/0011.png ('str' object has no attribute 'get')
Added unit tests, also tested locally with a dataset
No
N/A
=> Fix handling of invalid annotation descriptions and add tests to dataset uploads

.github/workflows/publish.yml
Publish mkdocs in gh-pages when a new release is created
- Locally, but just the build, to test it we need to create a new release
=> Publish mkdocs in gh-pages when a new release is created

.github/workflows/test.yml, roboflow/__init__.py, roboflow/util/folderparser.py, tests/test_version.py, tests/util/test_folderparser.py
Annotations are not uploaded because slashes don't match image filenames with our parse structure.
I'm forcing unix style slashes everywhere in folderparser.
* We have good tests for folderparser.
* I tested to upload images from local mac.
* I don't have a Windows to validate the fix. I'll ask the user to retry after release.
=> Normalize Windows style paths to parse folder

roboflow/__init__.py, roboflow/util/model_processor.py
Adds support for yolov7 model upload
- Locally
- Release
=> Adds support for yolov7 model upload

roboflow/__init__.py, roboflow/core/workspace.py
The previous message doesn't show any information about the error.
**Before:**
**After:**
- Localy
- Release app
=> Enhance error handling in model deployment URL retrieval

Dockerfile.dev
Upgrades the development container environment by updating Python from 3.8 to 3.10 and integrating uv as the package manager for faster dependency installation and better development experience.
Necessary because vscode debugger doesn't like python3.8 anymore
I can debug stuff in the devcontainer again :-)
Nope
N/A
=> Upgrade devcontainer

roboflow/adapters/rfapi.py, roboflow/core/project.py, roboflow/core/workspace.py, roboflow/models/inference.py
Fixes Python's common pitfall of using mutable objects (lists and dictionaries) as default function arguments. Mutable defaults are shared across function calls, which can lead to unexpected behavior when the default value is modified.
- Ran `make style` successfully
- Attempted `make check_code_quality` (blocked by missing stub packages)
- Attempted `python -m unittest` (blocked by missing dependencies)
No
None - this is a backward-compatible fix that prevents potential bugs without changing API behavior.
=> Fix mutable default arguments

pyproject.toml, requirements.txt, roboflow/__init__.py
Roboflow doesn't bound the pillow-hief version, resulting in the following errors when installed on Colab and kaggle notebooks:
```
12 
13 pillow_heif.register_heif_opener(thumbnails=False)  # Register for HEIF/HEIC
---> 14 pillow_heif.register_avif_opener(thumbnails=False)  # Register for AVIF
15 
16 
AttributeError: module 'pillow_heif' has no attribute 'register_avif_opener'
```
Tests pass.
Tested manually that 0.22 works (with a deprecation notice).
```python
>>> from PIL import Image
>>> import pillow_heif
>>> pillow_heif.__version__
'0.22.0'
>>> pillow_heif.register_avif_opener()
<stdin>:1: DeprecationWarning: The AVIF …
```
=> Fix #390: Lock `pillow-hief` version to not break AVIF support

.github/workflows/test.yml, requirements.txt, roboflow/__init__.py, roboflow/util/image_utils.py, tests/test_project.py
Use `pillow-avif-plugin` for AVIF instead of `pillow-heif`, because `pillow-heif>=1` removed AVIF support. See #390.
Remove Python 3.8 from CI because it is EOL for 8 months already. It still works, but there is no wheel for `pillow-avif-plugin`. I preferred to remove it instead of adding extra installs.
CI pass.
=> Use `pillow-avif-plugin` for AVIF support and support `pillow-heif` 1.0

roboflow/util/model_processor.py
Add new model sizes
Locally
No
=> Increase supported model types

roboflow/adapters/rfapi.py, roboflow/core/version.py, tests/manual/debugme.py, tests/test_version.py
The devx for training over the API was very broken. A simple snippet like below doesn't work. 
Nick uncovered this bug because Pella was bitten. [Slack thread](https://roboflow.slack.com/archives/C06TQCCTH41/p1754422279823959?thread_ts=1754413219.026309&cid=C06TQCCTH41)
This is one of those cases that just to debug, I had had to refactor first.
What actually solved the bug is:
* adding nocache=true to api calls
* waiting for version to have generating=False AND images>0 to consider it generated. Otherwise you can run into a very likely racing condition where the train endpoint finds a version that still looks empty.
```python
rf = Roboflow()
project = rf.workspace("meh3").project("mosquitobao")
version_number = project.generate_version(
settings={
"augmentation": {
"bbblur": {"pixels": …
```
=> Fix train-over-api devx

roboflow/__init__.py, roboflow/core/version.py, roboflow/util/versions.py, tests/util/test_versions.py
The format that was used to export before calling the train did not follow the current logic that exists in the backend. And the backend did not use modelType to calculate which link to train on.
locally, staging
None
-   [ ] Docs updated? What were the changes: None
=> Fixing format export for CLI/python sdk

roboflow/__init__.py, roboflow/core/workspace.py, tests/test_project.py
This flag allows dataset uploads to be sent as predictions (not automatically added to the dataset).
Unit tests cover this case
-   will need to update [relevant documentation](https://docs.roboflow.com/developer/upload-a-dataset)
=> Add are_predictions flag to dataset upload

roboflow/__init__.py, roboflow/core/workspace.py, tests/test_project.py
The `is_prediction` flag was not being passed to the correct function call, and thus was ignored. This correctly adds it to the `save_annotation` function call where it will be used downstream.
Unit tests
standard deploy 
-   n/a
=> fix is_prediction function call
